#!/bin/bash
# Migration from 0.9.0 to 1.0.0
# Adds vector search columns to database schema

set -euo pipefail

log_status "running" "migration" "Migrating database from 0.9.0 to 1.0.0..."

# Check if pgvector pod exists
if ! oc get pod pgvector-0 -n "$TARGET_NAMESPACE" >/dev/null 2>&1; then
  log_error "pgvector pod not found, cannot run migration"
fi

# Run SQL migration
log_status "running" "migration" "Adding vector search columns..."

oc exec -n "$TARGET_NAMESPACE" pgvector-0 -- psql -U postgres -d peoplemesh <<'SQL'
-- Enable pgvector extension if not already enabled
CREATE EXTENSION IF NOT EXISTS vector;

-- Add embedding column to profiles table
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS embedding vector(384);

-- Create vector index for semantic search
CREATE INDEX IF NOT EXISTS profiles_embedding_idx ON profiles
  USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);

-- Backfill embeddings for existing profiles (set to NULL, will be regenerated by app)
UPDATE profiles SET embedding = NULL WHERE embedding IS NULL;

-- Update schema version
CREATE TABLE IF NOT EXISTS schema_version (
  version VARCHAR(20) PRIMARY KEY,
  applied_at TIMESTAMP DEFAULT NOW()
);

INSERT INTO schema_version (version) VALUES ('1.0.0')
  ON CONFLICT (version) DO NOTHING;
SQL

if [[ $? -eq 0 ]]; then
  log_status "running" "migration" "Database migration complete"
else
  log_error "Database migration failed"
fi
