apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.applicationName }}-db-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.applicationName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: database
type: Opaque
stringData:
  username: {{ .Values.postgres.user | quote }}
  password: {{ .Values.postgres.password | quote }}
