apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.applicationName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.docling.service.port }}
      targetPort: {{ .Values.docling.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.applicationName }}
