apiVersion: v2
name: pgvector
description: PostgreSQL with pgvector extension for OpenShift
type: application
version: 0.1.0
appVersion: "15"
maintainers:
  - name: Peter Samouelian
    email: psamouel@redhat.com
sources:
  - https://github.com/francescopace/peoplemesh
