apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.model.name }}-view
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.model.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    opendatahub.io/dashboard: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.model.name }}-view-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.model.name }}-sa
