apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.model.name }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.model.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    opendatahub.io/dashboard: "true"
