apiVersion: v1
kind: Secret
metadata:
  name: default-name-{{ .Values.model.name }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.model.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    opendatahub.io/dashboard: "true"
  annotations:
    kubernetes.io/service-account.name: {{ .Values.model.name }}-sa
    openshift.io/display-name: default-name
type: kubernetes.io/service-account-token
